name: node_middleware lint
on:
  push:
    branches-ignore:
      - master

jobs:
  client-run-tests-and-lint:
    name: client lint and run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: cache deps
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install deps
        run: yarn install

      - name: run client unit tests use Jest
        run: yarn test
        working-directory: client

      - name: run lint in client
        run: yarn lint
        working-directory: client

  server-run-tests-and-lint:
    name: server lint and run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: cache deps
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install deps
        run: yarn install

      - name: run lint in server
        run: yarn lint
        working-directory: server
