name: deploy
on:
  push:
    branches:
      - master

jobs:
  upload-image:
    name: upload docker image to cloud
    needs:
      - server-run-tests-and-lint
      - client-run-tests-and-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: cache deps
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install deps
        run: yarn install

      - name: build client
        run: yarn build || yarn build
        working-directory: client

      - name: docker login
        run: docker login --username=${{ secrets.TENCENT_YUN_USERNAME }} --password ${{ secrets.TENCENT_YUN_PASSWORD }}

      - name: build docker image
        run: docker build -t wizard_node_middleware .

      - name: tag the image & push the image to cloud
        run: |
          docker tag $(docker images -q --filter reference=wizard_node_middleware) ${{ secrets.NODE_MIDDLEWARE_IMAGE_NAME }}
          docker push ${{ secrets.NODE_MIDDLEWARE_IMAGE_NAME }}

  pull-image:
    needs: [upload-image]
    name: pull image from cloud
    runs-on: ubuntu-latest
    steps:
      - name: deploy website
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          port: ${{ secrets.DEPLOY_SERVER_SSH_PORT }}
          script: |
            docker network create wizardoc_net
            docker login --username=${{ secrets.TENCENT_YUN_USERNAME }} --password ${{ secrets.TENCENT_YUN_PASSWORD }}
            docker stop ${{ secrets.NODE_MIDDLEWARE_CONTAINER_NAME }}
            docker rm -f ${{ secrets.NODE_MIDDLEWARE_CONTAINER_NAME }}
            docker rmi -f ${{ secrets.NODE_MIDDLEWARE_IMAGE_NAME }}
            docker pull ${{ secrets.NODE_MIDDLEWARE_IMAGE_NAME }}
            docker run -d --network wizardoc_net --name ${{ secrets.NODE_MIDDLEWARE_CONTAINER_NAME }} -p 3000:3000 ${{ secrets.NODE_MIDDLEWARE_IMAGE_NAME }}
